#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nix-project.nix-project-org2gfm \
    distribution.haskell-tags-nix-exe \
    nixpkgs.ansifilter \
    nixpkgs.coreutils \
    nixpkgs.gnugrep \
    nixpkgs.tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude links.org \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
