#!/bin/sh -eu

cd "$(dirname "$0")/.."

nix run \
    --ignore-environment \
    --keep LANG \
    --keep LOCALE_ARCHIVE \
    --file nix \
    nix-project-org2gfm \
    haskell-tags-nix-exe \
    ansifilter \
    coreutils \
    gnutar \
    gzip \
    tree \
    --command \
    org2gfm \
    --path-bin \
    --exclude links.org \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
